import { IPlatos } from "../../types";

export const Platos: IPlatos[] = [
  {
    id: "aa",
    nombre: "Niños Envueltos (Parra)",
    descripcion: "Porción de 12 Niños envueltos en Hoja de parra",
    precio: 6000,
    uri_img: "nino_parra",
    cantidad: 0,
    stock: 10,
  },
  {
    id: "ab",
    nombre: "Niños Envueltos (Repollo)",
    descripcion: "Porción de 12 Niños envueltos en Hoja de repollo",
    precio: 6000,
    uri_img: "nino_repollo",
    cantidad: 0,
    stock: 0,
  },
  {
    id: "ac",
    nombre: "Empanadas Arabe (cocida)",
    descripcion:
      "Docena de empanadas árabes cocidas Docena de empanadas árabes cocidas Docena de empanadas árabes cocidas Docena de árabes árabes empanadas árabes cocidas Docena de empanadas árabes cocidas Docena de empanadas árabes cocidas Docena de árabes árabes empanadas árabes cocidas Docena de empanadas árabes cocidas Docena de empanadas árabes cocidas Docena de empanadas árabes cocidas Docena de empanadas árabes cocidas",
    precio: 7500,
    uri_img: "empanada",
    cantidad: 0,
    stock: 10,
  },
  {
    id: "ad",
    nombre: "Kipe Relleno (cocido)",
    descripcion: "Porción de 3 Kipes cocidos",
    precio: 7500,
    uri_img: "kippe",
    cantidad: 0,
    stock: 0,
  },
  {
    id: "ae",
    nombre: "Pure de Garbanzo",
    descripcion: "porcion de pure de garbanzo",
    precio: 1000,
    uri_img: "garbanzo",
    cantidad: 0,
    stock: 10,
  },
  {
    id: "af",
    nombre: "Pure de Berenjena",
    descripcion: "porción de pure de berenjena",
    precio: 700,
    uri_img: "berenjena",
    cantidad: 0,
    stock: 10,
  },

  {
    id: "ag",
    nombre: "Tripa Rellena",
    descripcion: "Tripa rellena",
    precio: 6000,
    uri_img: "tripa",
    cantidad: 0,
    stock: 10,
  },
  {
    id: "ah",
    nombre: "Pan Arabe",
    descripcion: "Por unidad, panes de 20 cm de diametro",
    precio: 400,
    uri_img: "pan",
    cantidad: 0,
    stock: 10,
  },
  {
    id: "ai",
    nombre: "Empanadas Arabe (freezada)",
    descripcion: "Docena de empanadas árabe frezadas",
    precio: 6500,
    uri_img: "empanada",
    cantidad: 0,
    stock: 10,
  },
  {
    id: "aj",
    nombre: "Kipe Relleno (freezado)",
    descripcion: "Porción de 3 Kipes Frezados",
    precio: 6500,
    uri_img: "kippe",
    cantidad: 0,
    stock: 10,
  },
];
